# Generated by Django 6.0.2 on 2026-02-21 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_tenant_scope'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cart',
            new_name='orders_cart_tenant__4e13fb_idx',
            old_name='orders_cart_tenant_user_idx',
        ),
        migrations.RenameIndex(
            model_name='cart',
            new_name='orders_cart_tenant__ab8830_idx',
            old_name='orders_cart_tenant_session_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_tenant__291115_idx',
            old_name='orders_order_tenant_status_idx',
        ),
        migrations.AlterField(
            model_name='cart',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rows', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rows', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rows', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rows', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rows', to='tenants.tenant'),
        ),
    ]
