# Generated by Django 5.2.9 on 2026-02-06 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0010_alter_site_id_alter_sitecategory_id_alter_theme_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('version', models.CharField(max_length=50)),
                ('manifest_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('version', models.CharField(max_length=50)),
                ('manifest_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SitePlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_slug', models.SlugField()),
                ('activation_source', models.CharField(choices=[('manual', 'Manual'), ('template_required', 'Template Required'), ('dependency', 'Dependency')], max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_plugins', to='sites.site')),
            ],
            options={
                'unique_together': {('site', 'plugin_slug')},
            },
        ),
    ]
