# Generated by Django 5.2.9 on 2026-02-06 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0010_alter_site_id_alter_sitecategory_id_alter_theme_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
