# Generated by Django 5.2.9 on 2026-02-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='default_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
