# Generated by Django 5.2.9 on 2026-02-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_template_default_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='tag',
            field=models.CharField(blank=True, help_text='e.g. New, Special', max_length=50, null=True),
        ),
    ]
