# Generated by Django 5.2.9 on 2026-02-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_template_description_template_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
    ]
