# Generated by Django 5.2.9 on 2026-02-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_site_slug_alter_site_id_alter_sitecategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_covers/'),
        ),
    ]
