# Generated by Django 6.0.2 on 2026-02-06 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0008_alter_site_id_alter_site_owner_alter_sitecategory_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="template",
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=255, unique=True),
                ),
                (
                    "site_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of SiteCategory slugs this theme supports",
                    ),
                ),
                ("preview_image", models.ImageField(upload_to="theme_previews/")),
                ("preview_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        help_text="e.g. New, Special",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "source_identifier",
                    models.CharField(
                        help_text="Used by frontend to load theme assets",
                        max_length=255,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Modular theme configuration",
                    ),
                ),
                ("default_settings", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="themes",
                        to="sites.sitecategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="site",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sites",
                to="sites.theme",
            ),
        ),
        migrations.DeleteModel(
            name="Template",
        ),
    ]
