# Generated by Django 5.2.9 on 2026-02-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_remove_site_template_theme_site_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitecategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
