# Generated by Django 6.0.2 on 2026-02-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0010_alter_site_id_alter_sitecategory_id_alter_theme_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sitecategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
