# Generated by Django 6.0.2 on 2026-02-09 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_alter_site_id_alter_sitecategory_id_alter_theme_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_core', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='theme',
            name='required_plugins',
            field=models.ManyToManyField(blank=True, related_name='themes', to='sites.plugin'),
        ),
        migrations.CreateModel(
            name='SitePlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_plugins', to='sites.plugin')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_plugins', to='sites.site')),
            ],
            options={
                'unique_together': {('site', 'plugin')},
            },
        ),
    ]
