# Generated by Django 6.0.2 on 2026-02-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_plugin_theme_required_plugins_siteplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='is_usable',
            field=models.BooleanField(default=True),
        ),
    ]
