# Generated by Django 6.0.2 on 2026-02-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_plugin_is_usable'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
