# Generated by Django 6.0.2 on 2026-02-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0014_site_subscription_ends_at_site_trial_ends_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="meta_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="schema_type",
            field=models.CharField(blank=True, default="Restaurant", max_length=100),
        ),
        migrations.AddField(
            model_name="site",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
