# Generated by Django 6.0.2 on 2026-02-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_site_meta_description_site_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='provisioning_status',
            field=models.CharField(choices=[('optimizing_products', 'Optimizing Products'), ('preparing_settings', 'Preparing Settings'), ('setting_subdomain', 'Setting Subdomain'), ('receiving_ssl', 'Receiving SSL'), ('ready', 'Ready')], default='optimizing_products', max_length=50),
        ),
        migrations.AddField(
            model_name='site',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
