# Generated by Django 6.0.2 on 2026-02-13 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_site_provisioning_status_site_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=100, unique=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_subdomain_record', to='sites.site')),
            ],
        ),
    ]
