# Generated by Django 5.2.9 on 2026-02-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_product_price'),
        ('sites', '0004_alter_sitecategory_slug_alter_template_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, help_text='e.g. New, Special', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('site', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('site', 'slug')},
        ),
    ]
