// ============================================
// Mock Data for Development
// ============================================

import type {
  User,
  Restaurant,
  Plan,
  Category,
  Product,
  Theme,
  DashboardStats,
} from '@/types'

// Current User (Mock)
export const mockUser: User = {
  id: '1',
  email: 'ali@example.com',
  name: 'علی محمدی',
  phone: '09121234567',
  avatar: '/placeholder.svg?height=100&width=100',
  createdAt: new Date('2024-01-15'),
  updatedAt: new Date('2024-02-01'),
}

// Restaurant Data (Mock)
export const mockRestaurants: Restaurant[] = [
  {
    id: '1',
    ownerId: '1',
    name: 'کافه لذت',
    slug: 'cafe-lezzat',
    description: 'کافه‌ای دنج با بهترین قهوه‌های تخصصی',
    logo: '/placeholder.svg?height=200&width=200',
    coverImage: '/placeholder.svg?height=600&width=1200',
    address: 'تهران، خیابان ولیعصر، پلاک ۱۲۳',
    phone: '02112345678',
    email: 'info@cafe-lezzat.ir',
    socialLinks: {
      instagram: 'cafe_lezzat',
      telegram: 'cafe_lezzat',
      whatsapp: '09121234567',
    },
    settings: {
      themeId: 'minimal-cafe',
      primaryColor: '#1a1a1a',
      secondaryColor: '#f5f5f5',
      fontFamily: 'Vazirmatn',
      layoutVariant: 'grid',
      heroStyle: 'full',
      showPrices: true,
      currency: 'تومان',
      currencySymbol: 'ت',
      isPublished: true,
      customDomain: 'cafe-lezzat.ir',
    },
    subscription: {
      id: '1',
      planId: 'professional',
      status: 'active',
      startDate: new Date('2024-01-15'),
      endDate: new Date('2024-07-15'),
      autoRenew: true,
    },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '2',
    ownerId: '1',
    name: 'رستوران سنتی البرز',
    slug: 'alborz-traditional',
    description: 'تجربه اصیل طعم‌های ایرانی در فضایی سنتی و دلنشین',
    logo: '/placeholder.svg?height=200&width=200',
    coverImage: '/placeholder.svg?height=600&width=1200',
    address: 'تهران، خیابان شریعتی، بالاتر از پل رومی',
    phone: '02122334455',
    email: 'info@alborz-restaurant.ir',
    socialLinks: {
      instagram: 'alborz_traditional',
      telegram: 'alborz_traditional',
    },
    settings: {
      themeId: 'traditional-persian',
      primaryColor: '#1e3a5f',
      secondaryColor: '#f8f4e8',
      fontFamily: 'Vazirmatn',
      layoutVariant: 'grid',
      heroStyle: 'full',
      showPrices: true,
      currency: 'تومان',
      currencySymbol: 'ت',
      isPublished: true,
    },
    subscription: {
      id: '2',
      planId: 'professional',
      status: 'active',
      startDate: new Date('2024-01-15'),
      endDate: new Date('2024-07-15'),
      autoRenew: true,
    },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '3',
    ownerId: '1',
    name: 'رستوران مدرن اسکای',
    slug: 'sky-modern',
    description: 'ترکیبی از هنر آشپزی مدرن و چشم‌اندازی بی‌نظیر',
    logo: '/placeholder.svg?height=200&width=200',
    coverImage: '/placeholder.svg?height=600&width=1200',
    address: 'تهران، برج میلاد، طبقه گردان',
    phone: '02188990011',
    email: 'info@sky-modern.ir',
    socialLinks: {
      instagram: 'sky_modern',
    },
    settings: {
      themeId: 'modern-restaurant',
      primaryColor: '#2d3436',
      secondaryColor: '#dfe6e9',
      fontFamily: 'Vazirmatn',
      layoutVariant: 'grid',
      heroStyle: 'full',
      showPrices: true,
      currency: 'تومان',
      currencySymbol: 'ت',
      isPublished: true,
    },
    subscription: {
      id: '3',
      planId: 'enterprise',
      status: 'active',
      startDate: new Date('2024-01-15'),
      endDate: new Date('2024-07-15'),
      autoRenew: true,
    },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-01'),
  },
]

export const mockRestaurant = mockRestaurants[0]

// Subscription Plans
export const mockPlans: Plan[] = [
  {
    id: 'starter',
    name: 'استارتر',
    nameEn: 'Starter',
    description: 'مناسب برای شروع کسب‌وکار',
    price: 199000,
    duration: 30,
    features: [
      'حداکثر ۲۰ محصول',
      '۵ دسته‌بندی',
      'قالب پایه',
      'پشتیبانی ایمیلی',
      'زیردامنه رایگان',
    ],
    maxProducts: 20,
    maxCategories: 5,
    customDomain: false,
    analytics: false,
    support: 'basic',
  },
  {
    id: 'professional',
    name: 'حرفه‌ای',
    nameEn: 'Professional',
    description: 'مناسب برای رستوران‌های در حال رشد',
    price: 399000,
    duration: 30,
    features: [
      'حداکثر ۱۰۰ محصول',
      'دسته‌بندی نامحدود',
      'تمام قالب‌ها',
      'پشتیبانی اولویت‌دار',
      'دامنه اختصاصی',
      'آمار و گزارشات',
    ],
    isPopular: true,
    maxProducts: 100,
    maxCategories: -1,
    customDomain: true,
    analytics: true,
    support: 'priority',
  },
  {
    id: 'enterprise',
    name: 'سازمانی',
    nameEn: 'Enterprise',
    description: 'مناسب برای زنجیره‌های بزرگ',
    price: 799000,
    duration: 30,
    features: [
      'محصولات نامحدود',
      'دسته‌بندی نامحدود',
      'تمام قالب‌ها + اختصاصی',
      'پشتیبانی اختصاصی ۲۴/۷',
      'دامنه اختصاصی',
      'آمار پیشرفته',
      'API اختصاصی',
    ],
    maxProducts: -1,
    maxCategories: -1,
    customDomain: true,
    analytics: true,
    support: 'dedicated',
  },
]

// Categories
export const mockCategories: Category[] = [
  {
    id: '1',
    restaurantId: '1',
    name: 'نوشیدنی گرم',
    description: 'انواع قهوه و چای',
    image: '/placeholder.svg?height=200&width=200',
    order: 1,
    isActive: true,
  },
  {
    id: '2',
    restaurantId: '1',
    name: 'نوشیدنی سرد',
    description: 'انواع آیس‌کافی و اسموتی',
    image: '/placeholder.svg?height=200&width=200',
    order: 2,
    isActive: true,
  },
  {
    id: '3',
    restaurantId: '1',
    name: 'دسر',
    description: 'کیک و شیرینی',
    image: '/placeholder.svg?height=200&width=200',
    order: 3,
    isActive: true,
  },
  {
    id: '4',
    restaurantId: '1',
    name: 'صبحانه',
    description: 'منوی صبحانه',
    image: '/placeholder.svg?height=200&width=200',
    order: 4,
    isActive: true,
  },
]

// Products
export const mockProducts: Product[] = [
  // Hot Drinks
  {
    id: '1',
    restaurantId: '1',
    categoryId: '1',
    name: 'اسپرسو',
    description: 'اسپرسو تازه دم با دانه‌های عربیکا',
    price: 45000,
    image: '/placeholder.svg?height=300&width=300',
    isAvailable: true,
    isPopular: true,
    tags: ['تلخ', 'کافئین بالا'],
    order: 1,
  },
  {
    id: '2',
    restaurantId: '1',
    categoryId: '1',
    name: 'کاپوچینو',
    description: 'ترکیب عالی اسپرسو با شیر بخار داده',
    price: 65000,
    image: '/placeholder.svg?height=300&width=300',
    isAvailable: true,
    isPopular: true,
    tags: ['شیری', 'محبوب'],
    order: 2,
  },
  {
    id: '3',
    restaurantId: '1',
    categoryId: '1',
    name: 'لاته',
    description: 'اسپرسو با شیر فراوان و فوم نرم',
    price: 70000,
    image: '/placeholder.svg?height=300&width=300',
    isAvailable: true,
    tags: ['شیری', 'ملایم'],
    order: 3,
  },
  {
    id: '4',
    restaurantId: '1',
    categoryId: '1',
    name: 'موکا',
    description: 'ترکیب قهوه، شکلات و شیر',
    price: 75000,
    image: '/placeholder.svg?height=300&width=300',
    isAvailable: true,
    tags: ['شکلاتی', 'شیرین'],
    order: 4,
  },
  // Cold Drinks
  {
    id: '5',
    restaurantId: '1',
    categoryId: '2',
    name: 'آیس لاته',
    description: 'لاته سرد با یخ',
    price: 80000,
    image: '/placeholder.svg?height=300&width=300',
    isAvailable: true,
    isPopular: true,
    tags: ['سرد', 'تابستانی'],
    order: 1,
  },
  {
    id: '6',
    restaurantId: '1',
    categoryId: '2',
    name: 'اسموتی توت‌فرنگی',
    description: 'اسموتی تازه با توت‌فرنگی طبیعی',
    price: 95000,
    image: '/placeholder.svg?height=300&width=300',
    isAvailable: true,
    tags: ['میوه‌ای', 'تازه'],
    order: 2,
  },
  // Desserts
  {
    id: '7',
    restaurantId: '1',
    categoryId: '3',
    name: 'چیزکیک',
    description: 'چیزکیک خانگی با سس بلوبری',
    price: 85000,
    discountPrice: 75000,
    image: '/placeholder.svg?height=300&width=300',
    isAvailable: true,
    isPopular: true,
    tags: ['شیرین', 'خانگی'],
    order: 1,
  },
  {
    id: '8',
    restaurantId: '1',
    categoryId: '3',
    name: 'تیرامیسو',
    description: 'تیرامیسو ایتالیایی اصل',
    price: 90000,
    image: '/placeholder.svg?height=300&width=300',
    isAvailable: true,
    tags: ['قهوه‌ای', 'خامه‌ای'],
    order: 2,
  },
  // Breakfast
  {
    id: '9',
    restaurantId: '1',
    categoryId: '4',
    name: 'صبحانه انگلیسی',
    description: 'تخم‌مرغ، بیکن، نان تست و سالاد',
    price: 150000,
    image: '/placeholder.svg?height=300&width=300',
    isAvailable: true,
    tags: ['کامل', 'سیر کننده'],
    order: 1,
  },
  {
    id: '10',
    restaurantId: '1',
    categoryId: '4',
    name: 'پنکیک',
    description: 'پنکیک با شهد افرا و میوه',
    price: 95000,
    image: '/placeholder.svg?height=300&width=300',
    isAvailable: true,
    isPopular: true,
    tags: ['شیرین', 'صبحانه'],
    order: 2,
  },
]

// Themes/Templates
export const mockThemes: Theme[] = [
  {
    id: 1,
    name: 'کافه مینیمال',
    slug: 'minimal-cafe',
    description: 'طراحی ساده و مدرن برای کافه‌ها',
    preview_image: '/placeholder.svg?height=400&width=600',
    preview_url: '/preview/minimal-cafe',
    category: 1,
    category_name: 'کافه',
    site_types: ['cafe', 'restaurant'],
    source_identifier: 'minimal-cafe',
    config: {},
    default_settings: {
      primaryColor: '#1a1a1a',
      secondaryColor: '#f5f5f5',
      fontFamily: 'Vazirmatn',
    },
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'رستوران مدرن',
    slug: 'modern-restaurant',
    description: 'طراحی شیک برای رستوران‌های مدرن',
    preview_image: '/placeholder.svg?height=400&width=600',
    preview_url: '/preview/modern-restaurant',
    category: 2,
    category_name: 'رستوران',
    site_types: ['restaurant'],
    source_identifier: 'modern-restaurant',
    config: {},
    default_settings: {
      primaryColor: '#2d3436',
      secondaryColor: '#dfe6e9',
      fontFamily: 'Vazirmatn',
    },
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'رستوران سنتی ایرانی',
    slug: 'traditional-persian',
    description: 'طراحی با الهام از هنر ایرانی',
    preview_image: '/placeholder.svg?height=400&width=600',
    preview_url: '/preview/traditional-persian',
    category: 2,
    category_name: 'رستوران',
    site_types: ['restaurant'],
    source_identifier: 'traditional-persian',
    config: {},
    default_settings: {
      primaryColor: '#1e3a5f',
      secondaryColor: '#f8f4e8',
      fontFamily: 'Vazirmatn',
    },
    is_active: true,
    created_at: new Date().toISOString(),
  },
]

// Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalProducts: 10,
  totalCategories: 4,
  totalViews: 1250,
  todayViews: 45,
  subscriptionDaysLeft: 165,
}

// Helper function to format price in Persian
export function formatPrice(price: number): string {
  return new Intl.NumberFormat('fa-IR').format(price)
}

// Helper function to get Persian date
export function getPersianDate(date: Date): string {
  return new Intl.DateTimeFormat('fa-IR', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }).format(date)
}
